title: KJ4DIA
logo: /assets/img/kj4dia-high-resolution-color-logo.png
description: Michal Ferber - KJ4DIA - Technician Class License
show_downloads: false
google_analytics:
theme: jekyll-theme-minimal
